name: Audit Confidential Witness

on:
  workflow_dispatch:
  schedule:
    - cron: '17 9 * * *'
  push:
    branches:
      - main

jobs:
  audit-witness:
    runs-on: ubuntu-latest

    # Needed to auth with GCP
    permissions:
      contents: "write"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: "buoyant-breeze"
          workload_identity_provider: "projects/268995702429/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - run: mkdir -p buoyant-breeze

      - name: Run audit script
        working-directory: buoyant-breeze
        run: bash ../audit.sh
        env:
          PROJECT: buoyant-breeze

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Audit run"
          git push
